apiVersion: batch/v1
kind: Job
metadata:
  name: concept-sidecar-pattern
spec:
  template:
    spec:
      initContainers:
        - name: download-source-from-s3
          image: minio/mc:latest
          command: ["/bin/sh", "-c"]

          args:
            - |
              mc alias set minio http://minio:9000 minio minio123
              mc mirror minio/concept-car-bucket/source /source

          imagePullPolicy: Always
          volumeMounts:
            - name: source-dir
              mountPath: "/source"

        - name: core-container
          image: busybox:latest
          args: [ "cp", "-a", "source/.", "target/" ]
          imagePullPolicy: Always
          volumeMounts:
            - name: source-dir
              mountPath: "/source"
            - name: target-dir
              mountPath: "/target"

        - name: upload-target-to-s3
          image: minio/mc:latest

          command: ["/bin/sh", "-c"]

          args:
            - |
              mc alias set minio http://minio:9000 minio minio123
              mc mirror /target minio/concept-car-bucket/target

          imagePullPolicy: Always
          volumeMounts:
            - name: target-dir
              mountPath: "/target"

      containers:
         - name: empty
           image: busybox:latest
           command: ["sleep", "3600"]
           volumeMounts:
            - name: source-dir
              mountPath: "/source"
            - name: target-dir
              mountPath: "/target"

      volumes:
      - name: source-dir
        emptyDir: {}
      - name: target-dir
        emptyDir: {}

      restartPolicy: Never


  backoffLimit: 0
  ttlSecondsAfterFinished: 3600